// src/App.vue
<script setup lang="ts">
import { reactive, ref, nextTick, Ref  } from 'vue'
import Node from './components/node.vue'

let nodes    :any = reactive([1,2,3,4]);
let node_refs:any = reactive([]);

let active_item:Ref = ref(null);
let view_stat  :Ref = ref(false)

let onActiveItem = (index:any)=>{
    console.log(node_refs[index].node.id);
    
    if(active_item.value){
        active_item.value.node_view.children[0].style.fill = '#ddd';
    }
    active_item.value = node_refs[index];
    active_item.value.node_view.children[0].style.fill = 'red';
}

let pushNode = (node:any)=>{
    node_refs.push(node)
}

let onMouseDown = (e:any)=>{
    view_stat.value = true;
    
    if(e.which=='2'){
        // v-for ref 不会动态增加
        node_refs.length = 0;
        nodes.push(5)
    }
    if(e.which=='3'){
        // v-for ref 不会动态增加
        node_refs.length = 0;
        nodes.pop();
    }
}
let onMouseUp = (e:any)=>{
    view_stat.value = false;
}
let onMouseMove = (e:any)=>{
    if(view_stat.value === true && active_item.value){
        active_item.value.node_view.children[0].style.fill = `#${e.clientY}`;
        active_item.value.node_view.children[0].style.transform =`translate(${e.clientX}px, ${e.clientY}px)`;
        active_item.value.node_view.children[0].style.x = '0'
        active_item.value.node_view.children[0].style.y = '0'
    }
}

</script>

<template>
    <div style="margin:0;height:100vh;background-color:gray">
        <svg id="view" width="1000" height="900" style="margin:0;background-color:gray;"
            @mousedown="onMouseDown"
            @mouseup="onMouseUp"
            @mousemove="onMouseMove"
        >
            <text class="font" x='100' y='100'>Fiona</text>

            <Node 
                v-for="(node,index) in nodes" 
                :key="node" 
                :ref="pushNode"
                @click="onActiveItem(index)"
            />
        </svg>
    </div>
</template>

<style scoped>

</style>

// src/App.svelte
<script lang="ts">
    import Node from "./lib/node";

    let nodes: any = [];

    let init = () => {
        console.log("init...");

        nodes.push(new Node());
        nodes.push(new Node());
        nodes.push(new Node());
        console.log(nodes);
    };

    let current_active_item = null;
    let activeItem=(item)=>{
        if(current_active_item){
            current_active_item.view.children[0].style.fill = '#ddd';
        }
        current_active_item = item;
        item.view.children[0].style.fill = 'red';
    }

    let view_stat = false;
    let sceneMouseDown = (e)=>{
        console.log('down');
        view_stat = true;
    }
    let sceneMouseUp = (e)=>{
        console.log('up');
        view_stat = false;
    }
    let sceneMouseMove = (e)=>{
        if(view_stat === true && current_active_item){
            current_active_item.view.children[0].style.fill = `#${e.clientY}`;
            current_active_item.view.children[0].style.transform =`translate(${e.clientX}px, ${e.clientY}px)`;
            current_active_item.view.children[0].style.x = '0'
            current_active_item.view.children[0].style.y = '0'
        }
    }


    init();
</script>

<main style="background-color:gray">
    <div class="font" style="padding: 2vw 0 0 5vw">Fiona</div>
    <svg id="view" width="100vw" height="100vh" style="margin:0;"
        on:mousedown={sceneMouseDown}
        on:mouseup={sceneMouseUp}
        on:mousemove={sceneMouseMove}
    >
        {#each nodes as node}
            <!-- svelte-ignore a11y-click-events-have-key-events -->
            <g 
                bind:this={node.view}
                on:click={ ()=>{ activeItem(node) } }>
                
                <rect
                    x={node.x + "px"}
                    y={node.y + "px"}
                    rx="5px"
                    width="100"
                    height="40"
                    fill="#ddd"
                    stroke="black"
                    stroke-width=2
                    transform="translate(0, 0)"
                />
            </g>
        {/each}
    </svg>
</main>

<style>
</style>
